# language: generic
sudo: required
services:
    - docker
# only can test in dev
before_install:
    - docker build -t mpragarok/react-test -f ./client/Dockerfile.dev ./client
# run the test suite
script:
    - docker run -e CI=true mpragarok/react-test npm run test -- --coverage

after_success:
    - docker build -t mpragarok/multi-client ./client
    - docker build -t mpragarok/multi-nginx ./nginx
    - docker build -t mpragarok/multi-server ./server
    - docker build -t mpragarok/multi-worker ./worker
    # log in to the docker CLI
    - docker logout
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push those images to docker hub
    - docker push mpragarok/multi-client
    - docker push mpragarok/multi-nginx
    - docker push mpragarok/multi-server
    - docker push mpragarok/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "Multidocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-544101413601"
    bucket_path: "docker-multi"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
